2023-03-12 19:37:05,011 - ERROR - app.servercore - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\utilisateur\Desktop\brief-cicd\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\utilisateur\Desktop\brief-cicd\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\utilisateur\Desktop\brief-cicd\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\utilisateur\Desktop\brief-cicd\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\utilisateur\Desktop\brief-cicd\app\servercore.py", line 194, in index
    print(os.getcwd())
NameError: name 'os' is not defined
2023-03-12 19:37:31,557 - ERROR - app.servercore - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\utilisateur\Desktop\brief-cicd\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\utilisateur\Desktop\brief-cicd\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\utilisateur\Desktop\brief-cicd\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\utilisateur\Desktop\brief-cicd\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\utilisateur\Desktop\brief-cicd\app\servercore.py", line 194, in index
    print(os.getcwd())
NameError: name 'os' is not defined
2023-03-12 19:38:27,216 - ERROR - app.servercore - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\utilisateur\Desktop\brief-cicd\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\utilisateur\Desktop\brief-cicd\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\utilisateur\Desktop\brief-cicd\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\utilisateur\Desktop\brief-cicd\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\utilisateur\Desktop\brief-cicd\app\servercore.py", line 194, in index
    print(os.getcwd())
NameError: name 'os' is not defined
